# Generated by Django 3.2 on 2022-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
