# Generated by Django 3.2 on 2022-06-01 19:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
