# Generated by Django 3.2 on 2022-06-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_auto_20220601_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to='pic/%y/'),
        ),
    ]
