# Generated by Django 3.2 on 2022-06-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_auto_20220601_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
